/// `HEADER_COMMENT` is the generated file header.
pub const HEADER_COMMENT: &str = "DO NOT EDIT: Generated by baproto-gdscript";

/// `RUNTIME_PATH` is the path to the baproto runtime.
#[allow(dead_code)]
pub const RUNTIME_PATH: &str = "res://addons/baproto/runtime";

/// `SECTION_WIDTH` is the total width of section header comments.
#[allow(dead_code)]
const SECTION_WIDTH: usize = 80;

/* ------------------------ Fn: format_section_header ----------------------- */

/// `format_section_header` creates a section header like `-- NAME ---...--- #`.
#[allow(dead_code)]
pub(crate) fn format_section_header(name: &str) -> String {
    let prefix = "# ";
    let suffix = " #";
    let inner_width = SECTION_WIDTH - prefix.len() - suffix.len();

    // Calculate padding on both sides of the name.
    let name_with_spaces = format!(" {} ", name);
    let dashes_needed = inner_width.saturating_sub(name_with_spaces.len());
    let left_dashes = dashes_needed / 2;
    let right_dashes = dashes_needed - left_dashes;

    format!(
        "{}{}{}{}{}",
        prefix,
        "-".repeat(left_dashes),
        name_with_spaces,
        "-".repeat(right_dashes),
        suffix
    )
}

/* -------------------------------------------------------------------------- */
/*                                 Mod: Tests                                 */
/* -------------------------------------------------------------------------- */

#[cfg(test)]
mod tests {
    use super::*;

    /* ------------------ Tests: format_section_header ------------------ */

    #[test]
    fn test_format_section_header_short_name() {
        // Given: A short name.
        // When: Formatting as section header.
        let header = format_section_header("Test");

        // Then: Should be centered with dashes and total width 80.
        assert_eq!(header.len(), SECTION_WIDTH);
        assert!(header.contains(" Test "));
        assert!(header.starts_with("# -"));
        assert!(header.ends_with("- #"));
    }

    #[test]
    fn test_format_section_header_long_name() {
        // Given: A longer name.
        // When: Formatting as section header.
        let header = format_section_header("Very Long Section Name Here");

        // Then: Should be centered with minimal dashes.
        assert_eq!(header.len(), SECTION_WIDTH);
        assert!(header.contains(" Very Long Section Name Here "));
    }

    #[test]
    fn test_format_section_header_max_width() {
        // Given: A name that nearly fills the width.
        let long_name = "A".repeat(70);

        // When: Formatting as section header.
        let header = format_section_header(&long_name);

        // Then: Should still be exactly SECTION_WIDTH.
        assert_eq!(header.len(), SECTION_WIDTH);
    }
}
