use baproto::{Generator, GeneratorError, GeneratorOutput, Schema};

/* -------------------------------------------------------------------------- */
/*                              Struct: GDScript                              */
/* -------------------------------------------------------------------------- */

/// A code generator that produces GDScript bindings from Build-A-Proto schemas.
pub struct GDScript;

/* ----------------------------- Impl: Generator ---------------------------- */

impl Generator for GDScript {
    fn name(&self) -> &str {
        "gdscript"
    }

    fn generate(&self, _schema: &Schema) -> Result<GeneratorOutput, GeneratorError> {
        let mut output = GeneratorOutput::default();

        // TODO: Implement GDScript code generation. For now, just create a
        // placeholder file to verify the pipeline works
        output.add("test.gd", "# DO NOT EDIT: Generated by baproto-gdscript\n");

        Ok(output)
    }
}
